platform: linux
image_resource:
  type: registry-image
  source:
    repository: golang
    tag: 1.16-bullseye
inputs:
  - name: load-balancer-repo
  - name: server-emulator-gist
outputs:
  - name: binaries
run:
  path: 'bash'
  args:
  - -c
  - |
    set -e
    cd load-balancer-repo
    echo "building load balancer binary..."
    go get ./...
    go build -o lb
    cp lb ../binaries/lb
    echo "built load balancer binary"
    cd ../server-emulator-gist
    echo "building emulator binary..."
    go mod init emulator
    go get ./...
    go build -o emulator
    cp emulator ../binaries/emulator
    echo "built emulator binary"
    echo "installing netcat..."
    cat /etc/apt/sources.list
    sudo apt update -y
    apt install -y netcat
    nc --version
    cp $(which nc) ../binaries/nc
    echo "netcat installed"
